name: Renovate

permissions: read-all

on:
  schedule:
    # Run every 1 hours
    - cron: '0 * * * 1'
  workflow_dispatch:

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install requests pyjwt cryptography
      - name: Generate Matrix
        id: set-matrix
        env:
          RENOVATE_APP_ID: ${{ vars.RENOVATE_APP_ID }}
          RENOVATE_PRIVATE_KEY: ${{ secrets.RENOVATE_PRIVATE_KEY }}
          RENOVATE_USERNAME: ${{ vars.RENOVATE_USERNAME }}
          CODEBERG_BOT_USERNAME: ${{ vars.CODEBERG_BOT_USERNAME }}
          RENOVATE_INSTALLATION_WHITELIST: ${{ vars.RENOVATE_INSTALLATION_WHITELIST }}
        run: python .github/scripts/get_installations.py

  renovate:
    needs: discover
    name: Renovate (${{ matrix.platform }} - ${{ matrix.owner }})
    runs-on: ubuntu-latest
    concurrency:
      group: renovate-${{ matrix.platform }}-${{ matrix.owner }}
      cancel-in-progress: false
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        include: ${{ fromJson(needs.discover.outputs.matrix) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Cache Renovate
        uses: actions/cache@v5.0.1
        with:
          path: /tmp/renovate
          key: renovate-${{ matrix.platform }}-${{ matrix.owner }}-${{ github.run_id }}
          restore-keys: |
            renovate-${{ matrix.platform }}-${{ matrix.owner }}-

      - name: Fix Cache Permissions
        run: |
          sudo mkdir -p /tmp/renovate
          sudo chown -R 12021:0 /tmp/renovate

      - name: Make entrypoint executable
        run: chmod +x .github/renovate-entrypoint.sh

      - name: Get GitHub App Token
        if: matrix.platform == 'github'
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.RENOVATE_APP_ID }}
          private-key: ${{ secrets.RENOVATE_PRIVATE_KEY }}
          owner: ${{ matrix.owner }}

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v44.2.4
        with:
          configurationFile: renovate-config.js
          token: ${{ matrix.platform == 'github' && steps.app-token.outputs.token || secrets.CODEBERG_TOKEN }}
          renovate-version: 42.80.2-full
          docker-cmd-file: .github/renovate-entrypoint.sh
        env:
          RENOVATE_PLATFORM: ${{ matrix.platform }}
          RENOVATE_ENDPOINT: ${{ matrix.endpoint }}
          RENOVATE_USERNAME: ${{ matrix.renovate_username }}
          RENOVATE_GIT_AUTHOR: ${{ matrix.git_author }}
          RENOVATE_AUTODISCOVER_FILTER: ${{ vars.RENOVATE_AUTODISCOVER_FILTER }}
          LOG_LEVEL: debug

      - name: Fix Cache Permissions for Save
        if: always()
        run: |
          sudo chown -R $USER /tmp/renovate
