name: Renovate Worker

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      hashed_owner:
        required: true
        type: string
      endpoint:
        required: false
        type: string
      renovate_username:
        required: true
        type: string
      git_author:
        required: true
        type: string
    secrets:
      owner:
        required: false
      GOTHUB_APP_ID:
        required: false
      GOTHUB_PRIVATE_KEY:
        required: false
      CODEBERG_TOKEN:
        required: false
      GOTHUB_COM_TOKEN:
        required: false
      RENOVATE_AUTODISCOVER_FILTER:
        required: false
      RENOVATE_AUTODISCOVER_FILTER_GITHUB:
        required: false
      RENOVATE_AUTODISCOVER_FILTER_CODEBERG:
        required: false
      LOG_LEVEL:
        required: false

env:
  RENOVATE_VERSION: 44.35.4-full@sha256:66a265f4820edc6b9bd0e18439776c9ecf80a789ab8dcefc92bf7eb1afa0eb17

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Free Disk Space (Renovate)
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL

      - name: Restore Renovate Docker Image
        id: restore-renovate-image
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: renovate-image.tar.zst
          key: renovate-image-${{ env.RENOVATE_VERSION }}

      - name: Load Renovate Docker Image
        if: steps.restore-renovate-image.outputs.cache-hit == 'true'
        run: zstd -dc -T0 renovate-image.tar.zst | docker load

      - name: Cache Renovate
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: /tmp/renovate
          key: renovate-${{ inputs.platform }}-${{ inputs.hashed_owner }}-${{ github.run_id }}
          restore-keys: |
            renovate-${{ inputs.platform }}-${{ inputs.hashed_owner }}-

      - name: Fix Cache Permissions
        run: |
          sudo mkdir -p /tmp/renovate
          sudo chown -R 12021:0 /tmp/renovate

      - name: Get GitHub App Token
        if: inputs.platform == 'github'
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: generate_token
        with:
          client-id: ${{ secrets.GOTHUB_APP_ID || vars.GOTHUB_APP_ID }}
          private-key: ${{ secrets.GOTHUB_PRIVATE_KEY }}
          owner: ${{ secrets.owner }}

      - name: Self-hosted Renovate (GitHub)
        if: inputs.platform == 'github'
        uses: renovatebot/github-action@39b914146caeff8cd512e61c8992f1d5913af85c # v46.2.5
        with:
          configurationFile: renovate-config.js
          token: ${{ steps.generate_token.outputs.token }}
          renovate-version: ${{ env.RENOVATE_VERSION }}
        env:
          RENOVATE_PLATFORM: ${{ inputs.platform }}
          RENOVATE_ENDPOINT: ${{ inputs.endpoint }}
          RENOVATE_USERNAME: ${{ inputs.renovate_username }}
          RENOVATE_GIT_AUTHOR: ${{ inputs.git_author }}
          RENOVATE_AUTODISCOVER_FILTER: ${{ secrets.RENOVATE_AUTODISCOVER_FILTER_GITHUB || secrets.RENOVATE_AUTODISCOVER_FILTER || vars.RENOVATE_AUTODISCOVER_FILTER_GITHUB || vars.RENOVATE_AUTODISCOVER_FILTER }}
          LOG_LEVEL: ${{ secrets.LOG_LEVEL || vars.LOG_LEVEL || 'fatal' }}  # Defaults to max level to prevent info leaks on action log

      - name: Self-hosted Renovate (Codeberg)
        if: inputs.platform == 'forgejo'
        uses: renovatebot/github-action@39b914146caeff8cd512e61c8992f1d5913af85c # v46.2.5
        with:
          configurationFile: renovate-config.js
          token: ${{ secrets.CODEBERG_TOKEN }}
          renovate-version: ${{ env.RENOVATE_VERSION }}
        env:
          RENOVATE_PLATFORM: ${{ inputs.platform }}
          RENOVATE_ENDPOINT: ${{ inputs.endpoint }}
          RENOVATE_USERNAME: ${{ inputs.renovate_username }}
          RENOVATE_GIT_AUTHOR: ${{ inputs.git_author }}
          RENOVATE_AUTODISCOVER_FILTER: ${{ secrets.RENOVATE_AUTODISCOVER_FILTER_CODEBERG || secrets.RENOVATE_AUTODISCOVER_FILTER || vars.RENOVATE_AUTODISCOVER_FILTER_CODEBERG || vars.RENOVATE_AUTODISCOVER_FILTER }}
          RENOVATE_GITHUB_COM_TOKEN: ${{ secrets.GOTHUB_COM_TOKEN }}
          LOG_LEVEL: ${{ secrets.LOG_LEVEL || vars.LOG_LEVEL || 'fatal' }}  # Defaults to max level to prevent info leaks on action log

      - name: Fix Cache Permissions for Save
        if: always()
        run: |
          sudo chown -R $USER /tmp/renovate
