name: Renovate Worker

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      hashed_owner:
        required: true
        type: string
      endpoint:
        required: false
        type: string
      renovate_username:
        required: true
        type: string
      git_author:
        required: true
        type: string
    secrets:
      owner:
        required: false
      GOTHUB_APP_ID:
        required: false
      GOTHUB_PRIVATE_KEY:
        required: false
      CODEBERG_TOKEN:
        required: false
      RENOVATE_AUTODISCOVER_FILTER:
        required: false
      LOG_LEVEL:
        required: false

env:
  RENOVATE_VERSION: 42.81.5-full

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Free Disk Space (Renovate)
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL

      - name: Restore Renovate Docker Image
        id: restore-renovate-image
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          path: renovate-image.tar.zst
          key: renovate-image-${{ env.RENOVATE_VERSION }}

      - name: Load Renovate Docker Image
        if: steps.restore-renovate-image.outputs.cache-hit == 'true'
        run: zstd -dc -T0 renovate-image.tar.zst | docker load

      - name: Cache Renovate
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          path: /tmp/renovate
          key: renovate-${{ inputs.platform }}-${{ inputs.hashed_owner }}-${{ github.run_id }}
          restore-keys: |
            renovate-${{ inputs.platform }}-${{ inputs.hashed_owner }}-

      - name: Fix Cache Permissions
        run: |
          sudo mkdir -p /tmp/renovate
          sudo chown -R 12021:0 /tmp/renovate

      - name: Get GitHub App Token
        if: inputs.platform == 'github'
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: generate_token
        with:
          app-id: ${{ secrets.GOTHUB_APP_ID || vars.GOTHUB_APP_ID }}
          private-key: ${{ secrets.GOTHUB_PRIVATE_KEY }}
          owner: ${{ secrets.owner }}

      - name: Self-hosted Renovate (GitHub)
        if: inputs.platform == 'github'
        uses: renovatebot/github-action@693b9ef15eec82123529a37c782242f091365961 # v46.1.14
        with:
          configurationFile: renovate-config.js
          token: ${{ steps.generate_token.outputs.token }}
          renovate-version: ${{ env.RENOVATE_VERSION }}
        env:
          RENOVATE_PLATFORM: ${{ inputs.platform }}
          RENOVATE_ENDPOINT: ${{ inputs.endpoint }}
          RENOVATE_USERNAME: ${{ inputs.renovate_username }}
          RENOVATE_GIT_AUTHOR: ${{ inputs.git_author }}
          RENOVATE_AUTODISCOVER_FILTER: ${{ secrets.RENOVATE_AUTODISCOVER_FILTER || vars.RENOVATE_AUTODISCOVER_FILTER }}
          LOG_LEVEL: ${{ secrets.LOG_LEVEL || vars.LOG_LEVEL || 'fatal' }}  # Defaults to max level to prevent info leaks on action log

      - name: Self-hosted Renovate (Codeberg)
        if: inputs.platform == 'forgejo'
        uses: renovatebot/github-action@693b9ef15eec82123529a37c782242f091365961 # v46.1.14
        with:
          configurationFile: renovate-config.js
          token: ${{ secrets.CODEBERG_TOKEN }}
          renovate-version: ${{ env.RENOVATE_VERSION }}
        env:
          RENOVATE_PLATFORM: ${{ inputs.platform }}
          RENOVATE_ENDPOINT: ${{ inputs.endpoint }}
          RENOVATE_USERNAME: ${{ inputs.renovate_username }}
          RENOVATE_GIT_AUTHOR: ${{ inputs.git_author }}
          RENOVATE_AUTODISCOVER_FILTER: ${{ secrets.RENOVATE_AUTODISCOVER_FILTER || vars.RENOVATE_AUTODISCOVER_FILTER }}
          LOG_LEVEL: ${{ secrets.LOG_LEVEL || vars.LOG_LEVEL || 'fatal' }}  # Defaults to max level to prevent info leaks on action log

      - name: Fix Cache Permissions for Save
        if: always()
        run: |
          sudo chown -R $USER /tmp/renovate
